### ISSUE TITLE
Bootloader for STM32F4

### ISSUE THREAD

**Issue by svk4286** [gloomyandy/IAP#1]
Please tell me where to find the bootloader for STM32F407, or how to build from source?

**Comment by gloomyandy** [comment]
There isn't one. The only current bootloader is for the STM32H7 boards, all of the F4 boards we deal with already come with a suitable bootloader, so there has been no need for one.

**Comment by svk4286** [comment]
Thanks for the answer, but there is a makefile option for STMF4 in the source code.  Only I couldn't compile it. Tell me how to do it. Thanks.

**Comment by gloomyandy** [comment]
Just because there is an option does not mean it works. I've never built an STM32F4 bootloader from that code. The STM32F4 makefiles are there mainly to build the SBC IAP loader.

Why do you need a STM32F4 bootloader anyway? What board is it for?

**Comment by svk4286** [comment]
The processor on the FLY RRF E3 board burned out. I changed the processor, but I can't find the bootloader.

**Comment by gloomyandy** [comment]
Fly supplies the bootloader for his boards best to ask him for it.

**Comment by svk4286** [comment]
OK. While using Klipper. Thanks.
